<?php
/**
 * Plugin Name: British Mobile Tyres CRM Connector
 * Description: Securely transmits British Mobile Tyres WordPress enquiries to the CRM and preserves Google Ads attribution.
 * Version: 1.0.1
 * Author: British Mobile Tyres
 * Requires at least: 6.4
 * Requires PHP: 8.0
 */

declare(strict_types=1);
if (!defined('ABSPATH')) { exit; }
final class BMT_CRM_Connector {
    private const OPTION_KEY='bmt_crm_connector_options'; private const REST_NS='bmt-crm/v1'; private const COOKIE='bmt_attribution'; private const NONCE_ACTION='bmt_crm_lead'; private const ALLOWED_TYPES=['form','phone','whatsapp','purchase','other'];
    public static function init():void { add_action('admin_menu',[self::class,'admin_menu']); add_action('admin_init',[self::class,'register_settings']); add_action('rest_api_init',[self::class,'register_routes']); add_action('wp_enqueue_scripts',[self::class,'enqueue_assets']); add_action('wp_head',[self::class,'attribution_script'],1); }
    private static function options():array { return wp_parse_args((array)get_option(self::OPTION_KEY,[]),['api_url'=>'https://ads.britishmobiletyres.co.uk/api/leads.php','api_key'=>'','enabled'=>1]); }
    public static function register_settings():void { register_setting('bmt_crm_connector',self::OPTION_KEY,['type'=>'array','sanitize_callback'=>static fn($v):array=>['api_url'=>esc_url_raw((string)($v['api_url']??'')),'api_key'=>sanitize_text_field((string)($v['api_key']??'')),'enabled'=>!empty($v['enabled'])?1:0]]); }
    public static function admin_menu():void { add_options_page('BMT CRM Connector','BMT CRM','manage_options','bmt-crm-connector',[self::class,'settings_page']); }
    public static function settings_page():void { if(!current_user_can('manage_options'))return; $o=self::options(); $test=null; if(isset($_POST['bmt_test'])&&check_admin_referer('bmt_test_action')) $test=self::send_to_crm(['lead_type'=>'other','source'=>'wordpress-plugin-test','customer_name'=>'BMT CRM Connector Test','customer_phone'=>null,'customer_email'=>null,'service_requested'=>'CRM connection test','city'=>null,'postcode'=>null],['utm_source'=>'plugin_test','utm_medium'=>'test','utm_campaign'=>'bmt_crm_connector']); ?>
<div class="wrap"><h1>British Mobile Tyres CRM Connector</h1><?php if(is_array($test)): ?><div class="notice notice-<?php echo !empty($test['ok'])?'success':'error'; ?>"><p><?php echo esc_html($test['message']); ?></p></div><?php endif; ?><form method="post" action="options.php"><?php settings_fields('bmt_crm_connector'); ?><table class="form-table"><tr><th><label for="bmt_api_url">CRM API URL</label></th><td><input id="bmt_api_url" class="regular-text" type="url" name="<?php echo esc_attr(self::OPTION_KEY); ?>[api_url]" value="<?php echo esc_attr($o['api_url']); ?>"></td></tr><tr><th><label for="bmt_api_key">CRM API key</label></th><td><input id="bmt_api_key" class="regular-text" type="password" autocomplete="new-password" name="<?php echo esc_attr(self::OPTION_KEY); ?>[api_key]" value="<?php echo esc_attr($o['api_key']); ?>"></td></tr><tr><th>Connector enabled</th><td><label><input type="checkbox" name="<?php echo esc_attr(self::OPTION_KEY); ?>[enabled]" value="1" <?php checked((int)$o['enabled'],1); ?>> Enable lead transmission</label></td></tr></table><?php submit_button('Save settings'); ?></form><hr><h2>Connection test</h2><p>This creates one clearly labelled test lead in the CRM.</p><form method="post"><?php wp_nonce_field('bmt_test_action'); ?><input type="hidden" name="bmt_test" value="1"><?php submit_button('Send test lead','secondary'); ?></form></div><?php }
    public static function register_routes():void { register_rest_route(self::REST_NS,'/lead',['methods'=>'POST','callback'=>[self::class,'receive_lead'],'permission_callback'=>static function(WP_REST_Request $r):bool{$n=$r->get_header('X-WP-Nonce');return is_string($n)&&wp_verify_nonce($n,self::NONCE_ACTION)===1;}]); }
    public static function receive_lead(WP_REST_Request $request):WP_REST_Response { $body=$request->get_json_params(); if(!is_array($body))return new WP_REST_Response(['ok'=>false,'error'=>'Invalid JSON'],400); $lead=is_array($body['lead']??null)?$body['lead']:$body; $type=strtolower(trim((string)($lead['lead_type']??'form'))); if(!in_array($type,self::ALLOWED_TYPES,true))$type='other'; $clean=['lead_type'=>$type,'source'=>self::clean_source($lead['source']??'website'),'customer_name'=>self::clean_text($lead['customer_name']??'',160),'customer_phone'=>self::clean_text($lead['customer_phone']??'',60),'customer_email'=>sanitize_email((string)($lead['customer_email']??'')),'service_requested'=>self::clean_text($lead['service_requested']??'',200),'city'=>self::clean_text($lead['city']??'',100),'postcode'=>self::clean_text($lead['postcode']??'',20),'language'=>self::clean_text($lead['language']??get_locale(),10)]; foreach(['tyresize','vehicle_registration','registration','vehicle_reg'] as $k)if(isset($lead[$k])&&trim((string)$lead[$k])!=='')$clean['service_requested']=trim($clean['service_requested'].' | '.$k.': '.self::clean_text($lead[$k],80)); $attr=self::clean_attribution(is_array($body['attribution']??null)?$body['attribution']:[]); $result=self::send_to_crm($clean,$attr); return new WP_REST_Response($result,!empty($result['ok'])?201:502); }
    private static function send_to_crm(array $lead,array $attr):array { $o=self::options(); if(!(int)$o['enabled'])return['ok'=>false,'message'=>'CRM connector is disabled']; if($o['api_url']===''||$o['api_key']==='')return['ok'=>false,'message'=>'CRM API URL/key not configured']; $r=wp_remote_post($o['api_url'],['timeout'=>15,'redirection'=>2,'headers'=>['Content-Type'=>'application/json; charset=UTF-8','Accept'=>'application/json','X-BMT-LEAD-KEY'=>$o['api_key']],'body'=>wp_json_encode(['lead'=>$lead,'attribution'=>$attr]),'data_format'=>'body']); if(is_wp_error($r)){error_log('BMT CRM Connector: request failed: '.$r->get_error_message());return['ok'=>false,'message'=>'CRM request failed'];} $code=(int)wp_remote_retrieve_response_code($r); $json=json_decode((string)wp_remote_retrieve_body($r),true); if($code>=200&&$code<300&&is_array($json)&&!empty($json['ok']))return['ok'=>true,'lead_id'=>sanitize_text_field((string)($json['lead_id']??'')),'message'=>'Lead sent to CRM']; error_log('BMT CRM Connector: CRM rejected lead. HTTP '.$code); return['ok'=>false,'message'=>'CRM rejected the lead','status'=>$code]; }
    private static function clean_text($v,int $max):string{$v=sanitize_text_field((string)$v);return function_exists('mb_substr')?mb_substr($v,0,$max):substr($v,0,$max);} private static function clean_source($v):string{return self::clean_text($v?:'website',80);} private static function clean_attribution(array $a):array{$o=[];foreach(['gclid','gbraid','wbraid','utm_source','utm_medium','utm_campaign','utm_term','utm_content','landing_page','referrer'] as $k)if(isset($a[$k]))$o[$k]=self::clean_text($a[$k],in_array($k,['landing_page','referrer'],true)?1000:300);return $o;}
    public static function enqueue_assets():void { if(is_admin())return; wp_enqueue_script('bmt-crm-connector',plugins_url('assets/bmt-crm.js',__FILE__),[], '1.0.1',true); wp_localize_script('bmt-crm-connector','BMTCRM',['endpoint'=>esc_url_raw(rest_url(self::REST_NS.'/lead')),'nonce'=>wp_create_nonce(self::NONCE_ACTION)]); }
    public static function attribution_script():void { if(is_admin())return; $n=esc_js(self::COOKIE); ?><script>(function(){try{var p=new URLSearchParams(location.search),keys=['gclid','gbraid','wbraid','utm_source','utm_medium','utm_campaign','utm_term','utm_content'],a=JSON.parse(localStorage.getItem('<?php echo $n;?>')||'{}');keys.forEach(function(k){var v=p.get(k);if(v)a[k]=v});a.landing_page=a.landing_page||location.href;a.referrer=a.referrer||document.referrer||'';localStorage.setItem('<?php echo $n;?>',JSON.stringify(a))}catch(e){}})();</script><?php }
}
BMT_CRM_Connector::init();
