<?php

return [
    'mode' => 'audit_and_approval',
    'actions' => [
        [
            'key' => 'website_calls',
            'name' => 'BMT | Website Calls',
            'purpose' => 'Track eligible calls generated from the website.',
            'type' => 'PHONE_CALL_LEAD',
            'category' => 'LEAD',
            'primary' => true,
            'approval_required' => true,
        ],
        [
            'key' => 'click_to_call',
            'name' => 'BMT | Click to Call',
            'purpose' => 'Track clicks/taps on the website telephone link as an intent signal.',
            'type' => 'WEBPAGE',
            'category' => 'LEAD',
            'primary' => false,
            'approval_required' => true,
        ],
        [
            'key' => 'whatsapp_contact',
            'name' => 'BMT | WhatsApp Contact',
            'purpose' => 'Track website WhatsApp contact initiation.',
            'type' => 'WEBPAGE',
            'category' => 'LEAD',
            'primary' => false,
            'approval_required' => true,
        ],
        [
            'key' => 'lead_form',
            'name' => 'BMT | Lead Form Submitted',
            'purpose' => 'Track successful website lead form submissions.',
            'type' => 'WEBPAGE',
            'category' => 'LEAD',
            'primary' => true,
            'approval_required' => true,
        ],
        [
            'key' => 'purchase',
            'name' => 'BMT | Purchase Completed',
            'purpose' => 'Track completed purchases/paid jobs when a purchase value can be supplied.',
            'type' => 'WEBPAGE',
            'category' => 'PURCHASE',
            'primary' => true,
            'approval_required' => true,
        ],
    ],
    'automatic_creation' => false,
    'duplicate_check_required' => true,
    'production_activation_required' => true,
];
